global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using FastJwtAuth.Core.Entities;
global using MongoDB.Driver;
global using FastJwtAuth.MongoDB.Services;
global using FastJwtAuth.Core.Services;
global using MongoDB.Bson;
global using MongoDB.Driver.Linq;
global using Nopen.NET;
